<!-- 
		<div class="footer">	
		</div>
		<script src="layout/js/jquery-3.1.1.min"></script>
		<script src="layout/js/bootstrap.min.js"></script>
		<script src="layout/js/jquery-ui.min.js"></script>
		<script src="layout/js/jquery-selectBoxIt.min.js"></script>
		<script src="layout/js/backend.js"></script>
	</body>
</html> -->
				</div>
			   </div>
        <!-- /page content -->
           <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
		</div>
	</div>
    <!-- jQuery -->
    <script src="<?php echo $js;?>jquery-3.1.1.min.js"></script>
    <!-- Bootstrap -->
    <script src="<?php echo $js;?>bootstrap.min.js"></script>
    <!-- Datatables -->
    <script src="<?php echo $js;?>jquery.dataTables.min.js"></script>
    <script src="<?php echo $js;?>dataTables.bootstrap.min.js"></script>
    <script src="<?php echo $js;?>dataTables.responsive.min.js"></script> 
    <script src="<?php echo $js;?>responsive.bootstrap.js"></script>
    
    <script src="<?php echo $js;?>dataTables.scroller.min.js"></script>
    <!--file input-->
    <script src="<?php echo $js;?>fileinput.min.js"></script>
      <!-- Custom Theme Scripts -->
    <script src="<?php echo $js;?>custom.min.js"></script>
    <script src="<?php echo $js;?>backend.js"></script>
  
      <!-- scripts -->
      <?php get_script(); ?>

  
  

  </body>
</html>