<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php getTitle() ?></title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="<?php echo $css ;?>bootstrap.min.css "/>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?php echo $css ;?>font-awesome.min.css" />
        <!-- Datatables -->
    <link rel="stylesheet" href="<?php echo $css; ?>bootstrap.min.css" >
    <link rel="stylesheet" href="<?php echo $css; ?>bootstrap.min.css" >
    <link rel="stylesheet" href="<?php echo $css; ?>responsive.bootstrap.min.css" >
    <link rel="stylesheet" href="<?php echo $css; ?>scroller.bootstrap.min.css" >
    <!--file input-->
    <link rel="stylesheet" href="<?php echo $css; ?>fileinput.min.css" >
    <!-- Custom Theme Style -->
    <link rel="stylesheet" href="<?php echo $css;?>custom.min.css" >
  </head>	
  <body class="nav-md">
    
  	